### PR TITLE
Integrated Enhancements: Axios Helper Module, SEO Metadata Optimization, and React Hooks Refactoring

### PR DESCRIPTION
**Pull request by iGEVA**
This Pull Request implements comprehensive solutions across three key areas of the project: centralization of API calls through an Axios helper module, site-wide SEO metadata optimization, and transitioning to React hooks in authentication-related pages. These changes aim to improve code efficiency, search engine visibility, and adherence to modern React best practices.

**Axios Helper Module**:
- Developed a new Axios instance with default configurations to standardize API calls.
- Abstracted common API interactions into reusable functions to promote the DRY principle.
- Implemented error handling mechanisms within the Axios helper.

**SEO Metadata Optimization**:
- Updated meta tags, including descriptions, Open Graph, and Twitter Cards, to improve visibility and organic traffic.
- Reviewed canonical and hreflang tags for multilingual support, optimizing content presentation on social media and search engines.

**React Hooks Refactoring**:
- Identified and modified class components to function components, utilizing hooks such as useState, useEffect, and useContext.
- Conducted thorough testing to ensure there are no regressions on the pages affected by the refactoring.

**Testing and Validation**:
- Performed rigorous testing on API interactions with the new helper module, ensuring functionality across different environments.
- Validated SEO implementation using tools like Google's Structured Data Testing Tool, and reviewed by the SEO team.
- Exhaustively verified refactored authentication pages to confirm the absence of regressions.

With these changes, the project takes a step forward towards a cleaner architecture, increased online visibility, and an enhanced user experience, maintaining modern development best practices.

### CODE REVIEW

**Comment by System-Garcia** [comment]
**I can't accept it**

- No labels
- No project
- No milestone
- No issue

Please check your PR and change it

**Comment by iGEVA** [comment]
Changes done

**Comment by System-Garcia** [comment]
-  Select a Reviewer and one Assigned
- You should write a description.

Look at this example:
image

**Comment by System-Garcia** [comment]
You are also trying to merge with the Main branch

**Comment by iGEVA** [comment]
Thanks for the needed changes

**Review by System-Garcia — DISMISSED** [review]
thanks for your changes

**Review by System-Garcia — CHANGES_REQUESTED** [review]
Resolve conflicts

**Comment by iGEVA** [comment]
Now is all done

**Review by System-Garcia — APPROVED** [review]

**Pull request merged**
