### PR TITLE
feat: setlement of environtment variables

### PR DESCRIPTION
**Pull request by iGEVA**
This Pull Request introduces the use of environment variables for frontend configuration, allowing dynamic adaptation to various deployment environments such as development, staging, and production. This approach enhances the flexibility and security of the application's configuration without requiring code changes for each environment.

**Changes Made**:
- **Environment Variables Definition**: A `.env` file has been created at the root of the frontend project, listing all necessary environment variables, such as `REACT_APP_API_BASE_URL`, used throughout the application for API requests.
- **Secure Integration of `.env` Variables**: The variables defined in the `.env` file have been securely integrated into the application's codebase, especially where API URLs or other configurable settings are required.
- **Documentation of Environment Variables Usage**: The project's README file has been updated to include instructions on how to set up the `.env` file, which variables are required, and potentially what the expected values might be for different environments.
- **Testing Across Environments**: The application has been verified to correctly pick up values from the `.env` file in various environments, including local development, CI/CD pipelines, and production servers.

This approach ensures that the frontend configuration is more manageable and secure, facilitating the handling of changes across different environments without compromising security or requiring code adjustments.

### CODE REVIEW

**Comment by System-Garcia** [comment]
I can't accept it

No labels
No project
No milestone
No issue
Please check your PR and change it

**Comment by iGEVA** [comment]
Changes done

**Comment by System-Garcia** [comment]
-  Select a Reviewer and one Assigned
- You should write a description.

Look at this example:
image

**Comment by iGEVA** [comment]
Thank you for your reviews 💯

**Review by System-Garcia — APPROVED** [review]
thanks for your changes, all is well

**Pull request merged**
